/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/email/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request email login or registration code
         * @description Always returns the same public response and does not disclose whether an email exists.
         */
        post: operations["requestEmailCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email code and create session */
        post: operations["verifyEmailCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start OAuth authorization */
        get: operations["startOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Complete OAuth authorization */
        get: operations["completeOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create local development session
         * @description Available only outside production when AUTH_DEV_LOGIN_ENABLED=true.
         */
        post: operations["devLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get private current user profile */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update private current user profile */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/profiles/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public profile by username */
        get: operations["getPublicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search public profiles by username or display name */
        get: operations["searchPeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create article draft */
        post: operations["createArticleDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user articles */
        get: operations["listMyArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/drafts/{articleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get own article draft */
        get: operations["getArticleDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update own article draft and create new revision */
        patch: operations["updateArticleDraft"];
        trace?: never;
    };
    "/articles/drafts/{articleId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit draft for moderation or direct publication */
        post: operations["submitArticleDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/drafts/{articleId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive own draft or moderation submission */
        post: operations["archiveArticleDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{articleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get published article */
        get: operations["getPublishedArticle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published feed articles */
        get: operations["listFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List popular articles from the last 14 days */
        get: operations["listPopularFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List personalized feed articles for current user */
        get: operations["listMyFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search published articles with PostgreSQL fallback search */
        get: operations["searchArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{articleId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List article comments */
        get: operations["listArticleComments"];
        put?: never;
        /** Create article comment */
        post: operations["createArticleComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get comment by id */
        get: operations["getComment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit own comment during edit window */
        patch: operations["updateComment"];
        trace?: never;
    };
    "/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set or remove reaction */
        post: operations["setReaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookmarks/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookmark lists */
        get: operations["listBookmarkLists"];
        put?: never;
        /** Create bookmark list */
        post: operations["createBookmarkList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookmarks/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookmarked published articles */
        get: operations["listBookmarkedArticles"];
        put?: never;
        /** Add article to bookmark list */
        post: operations["addBookmark"];
        /** Remove article from bookmark list */
        delete: operations["removeBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{authorID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow author */
        post: operations["followAuthor"];
        /** Unfollow author */
        delete: operations["unfollowAuthor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending reports for moderators */
        get: operations["listReports"];
        put?: never;
        /** Create article or comment report */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportID}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add moderation decision to report */
        post: operations["decideReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending article moderation submissions */
        get: operations["listModerationSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/submissions/{submissionID}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve article moderation submission */
        post: operations["approveModerationSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/submissions/{submissionID}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject article moderation submission */
        post: operations["rejectModerationSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/submissions/{submissionID}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List moderation threads for submission */
        get: operations["listModerationThreads"];
        put?: never;
        /** Create moderation thread */
        post: operations["createModerationThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/threads/{threadID}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve moderation thread */
        post: operations["resolveModerationThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderation/threads/{threadID}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen moderation thread */
        post: operations["reopenModerationThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user notifications */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get unread notification count */
        get: operations["getUnreadNotificationCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream current user notification counters */
        get: operations["streamNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationID}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark notification as read */
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark notifications for target as read */
        post: operations["markTargetNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user chat conversations */
        get: operations["listChatConversations"];
        put?: never;
        /** Start or return direct chat conversation */
        post: operations["startChatConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/conversations/{conversationID}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List chat messages */
        get: operations["listChatMessages"];
        put?: never;
        /** Send chat message */
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/conversations/{conversationID}/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream chat messages */
        get: operations["streamChatMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/conversations/{conversationID}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark chat conversation as read */
        post: operations["markChatConversationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload media file */
        post: operations["uploadMediaFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/files/{fileID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get media file metadata */
        get: operations["getMediaFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/files/{fileID}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download media file content */
        get: operations["getMediaFileContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/files/{fileID}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download media preview */
        get: operations["getMediaFilePreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequestEmailCodeRequest: {
            /** Format: email */
            email: string;
        };
        RequestEmailCodeResponse: {
            /** @enum {string} */
            status: "accepted";
            /** @description Present only outside production when AUTH_DEV_EMAIL_CODE_IN_RESPONSE=true. */
            dev_code?: string;
        };
        VerifyEmailCodeRequest: {
            /** Format: email */
            email: string;
            code: string;
        };
        DevLoginRequest: {
            /**
             * Format: email
             * @default dev@catch.local
             */
            email: string;
        };
        CurrentUserResponse: {
            user: components["schemas"]["User"];
            capabilities: components["schemas"]["Capabilities"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            username?: string;
            display_name?: string;
            /** Format: uri */
            avatar_url?: string;
            rating: number;
            /** @enum {string} */
            role: "user" | "admin";
        };
        Capabilities: {
            can_create_article: boolean;
            can_comment: boolean;
            can_chat: boolean;
            can_report: boolean;
            can_publish_directly: boolean;
            can_moderate: boolean;
            can_chat_with_dev_lead: boolean;
        };
        PrivateProfile: {
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            username?: string;
            display_name?: string;
            /** Format: uri */
            avatar_url?: string;
            rating: number;
            /** @enum {string} */
            role: "user" | "admin";
            /** Format: date */
            birth_date?: string;
            bio?: string;
            boat?: string;
            country_code?: string;
            country_name?: string;
            city_name?: string;
        };
        PublicProfile: {
            /** Format: uuid */
            user_id: string;
            username?: string;
            display_name?: string;
            /** Format: uri */
            avatar_url?: string;
            rating: number;
            bio?: string;
            boat?: string;
            country_name?: string;
            city_name?: string;
        };
        ProfileSearch: {
            items: components["schemas"]["PublicProfile"][];
        };
        UpdateMyProfileRequest: {
            username?: string;
            display_name?: string;
            /** Format: uri */
            avatar_url?: string;
            /**
             * Format: date
             * @description Empty string clears the value.
             */
            birth_date?: string;
            bio?: string;
            boat?: string;
            country_code?: string;
            country_name?: string;
            city_name?: string;
        };
        ArticleDocument: {
            /** @constant */
            type: "catch.article";
            version: number;
            blocks: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        CreateDraftRequest: {
            title: string;
            content?: components["schemas"]["ArticleDocument"];
            tags?: string[];
        };
        UpdateDraftRequest: {
            title?: string;
            content?: components["schemas"]["ArticleDocument"];
            tags?: string[];
        };
        SubmitDraftRequest: {
            /** Format: date-time */
            publish_at?: string;
        };
        ArticleDraft: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "draft" | "in_moderation" | "ready_to_publish" | "published" | "archived" | "removed";
            /** Format: uuid */
            current_revision_id: string;
            moderation_required: boolean;
            title: string;
            content: components["schemas"]["ArticleDocument"];
            excerpt: string;
            /** Format: uri-reference */
            cover_url?: string;
            tags: string[];
            version: number;
            /** Format: date-time */
            scheduled_at?: string;
            /** Format: date-time */
            published_at?: string;
        };
        ArticleDraftList: {
            items: components["schemas"]["ArticleDraft"][];
        };
        PublicArticle: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            author_id: string;
            title: string;
            content: components["schemas"]["ArticleDocument"];
            excerpt: string;
            /** Format: uri-reference */
            cover_url?: string;
            tags: string[];
            reactions_up: number;
            reactions_down: number;
            reaction_score: number;
            /** Format: date-time */
            published_at: string;
        };
        ArticleList: {
            items: components["schemas"]["ArticleListItem"][];
            next_cursor?: string;
        };
        ArticleListItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            author_id: string;
            title: string;
            excerpt: string;
            /** Format: uri-reference */
            cover_url?: string;
            tags: string[];
            reactions_up: number;
            reactions_down: number;
            reaction_score: number;
            /** Format: date-time */
            published_at: string;
        };
        CreateCommentRequest: {
            /** Format: uuid */
            parent_id?: string;
            body: string;
        };
        UpdateCommentRequest: {
            body: string;
        };
        Comment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            article_id: string;
            /** Format: uuid */
            author_id: string;
            /** Format: uuid */
            parent_id?: string;
            body: string;
            /** @enum {string} */
            status: "active" | "deleted";
            reactions_up: number;
            reactions_down: number;
            reaction_score: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            edited_at?: string;
        };
        CommentList: {
            items: components["schemas"]["Comment"][];
        };
        SetReactionRequest: {
            /** @enum {string} */
            target_type: "article" | "comment";
            /** Format: uuid */
            target_id: string;
            /** @enum {integer} */
            value: -1 | 0 | 1;
        };
        Reaction: {
            /** @enum {string} */
            target_type: "article" | "comment";
            /** Format: uuid */
            target_id: string;
            /** @enum {integer} */
            value: -1 | 0 | 1;
            reactions_up: number;
            reactions_down: number;
            reaction_score: number;
        };
        BookmarkList: {
            /** Format: uuid */
            id: string;
            name: string;
            position: number;
        };
        BookmarkLists: {
            items: components["schemas"]["BookmarkList"][];
        };
        CreateBookmarkListRequest: {
            name: string;
        };
        AddBookmarkRequest: {
            /** Format: uuid */
            list_id?: string;
            /** Format: uuid */
            article_id: string;
        };
        RemoveBookmarkRequest: {
            /** Format: uuid */
            list_id: string;
            /** Format: uuid */
            article_id: string;
        };
        BookmarkedArticle: {
            /** Format: uuid */
            list_id: string;
            list_name: string;
            /** Format: uuid */
            article_id: string;
            /** Format: uuid */
            author_id: string;
            title: string;
            excerpt: string;
            tags: string[];
            /** Format: date-time */
            published_at: string;
            /** Format: date-time */
            bookmarked_at: string;
        };
        BookmarkedArticles: {
            items: components["schemas"]["BookmarkedArticle"][];
        };
        FollowState: {
            /** Format: uuid */
            author_id: string;
            following: boolean;
        };
        CreateReportRequest: {
            /** @enum {string} */
            target_type: "article" | "comment";
            /** Format: uuid */
            target_id: string;
            /** @enum {string} */
            reason: "advertising" | "profanity" | "insult" | "fraud" | "other";
            details?: string;
        };
        DecideReportRequest: {
            /** @enum {string} */
            decision: "accept" | "reject";
        };
        Report: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            target_type: "article" | "comment";
            /** Format: uuid */
            target_id: string;
            /** Format: uuid */
            reporter_id: string;
            /** @enum {string} */
            reason: "advertising" | "profanity" | "insult" | "fraud" | "other";
            details: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "rejected";
            /** Format: date-time */
            created_at: string;
        };
        ReportList: {
            items: components["schemas"]["Report"][];
        };
        RejectModerationSubmissionRequest: {
            reason: string;
        };
        CreateModerationThreadRequest: {
            block_id?: string;
            body: string;
        };
        ReopenModerationThreadRequest: {
            reason?: string;
        };
        ModerationSubmission: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            article_id: string;
            /** Format: uuid */
            revision_id: string;
            /** Format: uuid */
            author_id: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "cancelled";
            rejection_reason: string;
            approval_count: number;
            open_thread_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ModerationSubmissionList: {
            items: components["schemas"]["ModerationSubmission"][];
        };
        ModerationThread: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            submission_id: string;
            /** Format: uuid */
            author_id: string;
            block_id?: string;
            body: string;
            /** @enum {string} */
            status: "open" | "resolved";
            /** Format: date-time */
            created_at: string;
        };
        ModerationThreadList: {
            items: components["schemas"]["ModerationThread"][];
        };
        Notification: {
            /** Format: uuid */
            id: string;
            event_type: string;
            target_type?: string;
            target_id?: string;
            title: string;
            body: string;
            unread_count: number;
            /** Format: date-time */
            read_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        NotificationList: {
            items: components["schemas"]["Notification"][];
            unread_total: number;
        };
        UnreadNotificationCount: {
            unread_total: number;
        };
        MarkTargetReadRequest: {
            target_type: string;
            target_id: string;
        };
        StartChatConversationRequest: {
            /** Format: uuid */
            recipient_id: string;
        };
        SendChatMessageRequest: {
            body: string;
        };
        ChatConversation: {
            /** Format: uuid */
            id: string;
            member_ids: string[];
            unread_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ChatConversationList: {
            items: components["schemas"]["ChatConversation"][];
        };
        ChatMessage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id: string;
            /** Format: uuid */
            sender_id: string;
            body: string;
            /** @enum {string} */
            status: "sent" | "read";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            read_at?: string;
        };
        ChatMessageList: {
            items: components["schemas"]["ChatMessage"][];
        };
        MediaFile: {
            /** Format: uuid */
            id: string;
            original_name: string;
            /** @enum {string} */
            mime_type: "image/jpeg" | "image/png" | "image/webp" | "image/gif" | "application/pdf";
            size_bytes: number;
            width?: number;
            height?: number;
            url: string;
            preview_url?: string;
            /** Format: date-time */
            created_at: string;
        };
        ErrorResponse: {
            type: string;
            title: string;
            status: number;
            /** @enum {string} */
            code: "invalid_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "not_implemented" | "service_unavailable" | "internal_error";
            message: string;
            trace_id?: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated user has no permission for this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Validation failed */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Service is temporarily unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        OAuthProvider: "google" | "vk" | "yandex";
        ArticleId: string;
        Limit: number;
        /** @description Opaque cursor from previous list response. */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestEmailCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestEmailCodeRequest"];
            };
        };
        responses: {
            /** @description Email code request accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestEmailCodeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    verifyEmailCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailCodeRequest"];
            };
        };
        responses: {
            /** @description Authenticated user */
            200: {
                headers: {
                    /** @description HttpOnly session cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    startOAuth: {
        parameters: {
            query?: {
                return_to?: string;
            };
            header?: never;
            path: {
                provider: components["parameters"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to OAuth provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    completeOAuth: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                provider: components["parameters"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect back to web app with session cookie */
            302: {
                headers: {
                    /** @description HttpOnly session cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    devLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated dev user */
            200: {
                headers: {
                    /** @description HttpOnly session cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyProfileRequest"];
            };
        };
        responses: {
            /** @description Updated private profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    getPublicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    searchPeople: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching public profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSearch"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    createArticleDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftRequest"];
            };
        };
        responses: {
            /** @description Created draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDraft"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    listMyArticles: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                after_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDraftList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getArticleDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                articleId: components["parameters"]["ArticleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDraft"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateArticleDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                articleId: components["parameters"]["ArticleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDraftRequest"];
            };
        };
        responses: {
            /** @description Updated draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDraft"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    submitArticleDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                articleId: components["parameters"]["ArticleId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SubmitDraftRequest"];
            };
        };
        responses: {
            /** @description Submitted draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDraft"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveArticleDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                articleId: components["parameters"]["ArticleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDraft"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getPublishedArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                articleId: components["parameters"]["ArticleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published article */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicArticle"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listFeed: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque cursor from previous list response. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feed articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listPopularFeed: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Popular feed articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listMyFeed: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque cursor from previous list response. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Personalized feed articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    searchArticles: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                /** @description Opaque cursor from previous list response. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleList"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    listArticleComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                articleId: components["parameters"]["ArticleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createArticleComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                articleId: components["parameters"]["ArticleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description Created comment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    getComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentRequest"];
            };
        };
        responses: {
            /** @description Updated comment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    setReaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetReactionRequest"];
            };
        };
        responses: {
            /** @description Reaction state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    listBookmarkLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark lists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkLists"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createBookmarkList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookmarkListRequest"];
            };
        };
        responses: {
            /** @description Created bookmark list */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listBookmarkedArticles: {
        parameters: {
            query?: {
                list_id?: string;
                q?: string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmarked articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkedArticles"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddBookmarkRequest"];
            };
        };
        responses: {
            /** @description Bookmark added */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    removeBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveBookmarkRequest"];
            };
        };
        responses: {
            /** @description Bookmark removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    followAuthor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Follow state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowState"];
                };
            };
        };
    };
    unfollowAuthor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Follow state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowState"];
                };
            };
        };
    };
    listReports: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending reports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description Created report */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    decideReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideReportRequest"];
            };
        };
        responses: {
            /** @description Report state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listModerationSubmissions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending submissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationSubmissionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    approveModerationSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationSubmission"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectModerationSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectModerationSubmissionRequest"];
            };
        };
        responses: {
            /** @description Submission state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationSubmission"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listModerationThreads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moderation threads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationThreadList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createModerationThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModerationThreadRequest"];
            };
        };
        responses: {
            /** @description Created moderation thread */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationThread"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    resolveModerationThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationThread"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reopenModerationThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReopenModerationThreadRequest"];
            };
        };
        responses: {
            /** @description Thread state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationThread"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUnreadNotificationCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unread count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadNotificationCount"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    streamNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events with unread notification counter updates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification marked read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    markTargetNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkTargetReadRequest"];
            };
        };
        responses: {
            /** @description Target notifications marked read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listChatConversations: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatConversationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    startChatConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartChatConversationRequest"];
            };
        };
        responses: {
            /** @description Chat conversation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatConversation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listChatMessages: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                conversationID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendChatMessageRequest"];
            };
        };
        responses: {
            /** @description Chat message */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    streamChatMessages: {
        parameters: {
            query?: {
                after_id?: string;
            };
            header?: never;
            path: {
                conversationID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events with ready, ping and message events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    markChatConversationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation marked read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadMediaFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded media file */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getMediaFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media file metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFile"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMediaFileContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media file content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                    "image/gif": string;
                    "application/pdf": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMediaFilePreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media preview image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/webp": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
